POST http://localhost:5293/api/auth/register
Content-Type: application/json

{
  "userName": "dery_admin",
  "password": "password123",
  "dataUser": "{ \"role\": \"admin\", \"status\": \"active\" }"
}